# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Basci Tests

on:
  push:
    branches: [ master, ci-develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8 
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.8.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unittests
      run: python -m unittest discover -s ./core/tests -p "*Tests.py"
    - name: Run critical tests
      run: |
        echo $PWD
        ls
        python -c "import core"
        PYTHONPATH="$PWD"
        sudo python runtests_critical.py
